version: 2
jobs:
  update-and-publish:
    docker:
      - image:  rocker/tidyverse
      
    steps: 
      - checkout
      - run:
          name: Get the data
          command: |
             R -e "rmarkdown::render('index.Rmd',output_file='index.html')"

workflows:
    version: 2
    daily:
        jobs:
            - update-and-publish
        triggers:
            - schedule:
                cron: 10 10 * * *
                filters:
                    branches:
                        only:
                            - master
